import { beforeAll, describe, expect, it } from "vitest";
import { exports } from "cloudflare:workers";
import { ensureMigrations } from "../migrate.js";
import {
  pluginListResponseSchema,
  pluginRegistryDescriptorSchema,
} from "../../src/contract/api/plugins.js";

/**
 * #382 the minimal plugin serving face: the static registry entry parses
 * against the ported installedPlugin schema (the bb SPA's SDK client
 * zod-parses this response — packages/sdk/src/areas/plugins.ts:438-441 — so
 * any drift is a SPA-side settings-nav crash), and the asset route serves
 * the built bundle bytes with bb's hash-busting cache policy.
 *
 * The descriptor fixture (test/fixtures/spa-root/plugins/cap-provider-config/)
 * mirrors what scripts/stage-bb-spa.sh stages next to the real bundle.
 */

beforeAll(ensureMigrations);

const BASE = "https://example.com";
const FIXTURE_HASH = "0123456789abcdef";

async function request(path: string): Promise<Response> {
  return exports.default.fetch(`${BASE}${path}`);
}

describe("static plugin registry", () => {
  it("serves the descriptor-tracked entry through the installedPlugin schema", async () => {
    const response = await request("/api/v1/plugins");
    expect(response.status).toBe(200);
    const body = pluginListResponseSchema.parse(await response.json());
    expect(body.plugins).toHaveLength(1);
    const [plugin] = body.plugins;
    if (plugin === undefined) throw new Error("registry list came back empty");
    expect(plugin.id).toBe("cap-provider-config");
    expect(plugin.status).toBe("running");
    expect(plugin.enabled).toBe(true);
    // The SPA candidate filter (plugin-frontend.ts:312-316) reads exactly
    // this slice: status running + a servable bundle.
    expect(plugin.app.hasApp).toBe(true);
    expect(plugin.app.bundle).not.toBeNull();
    expect(plugin.app.bundle?.jsUrl).toBe(
      `/api/v1/plugins/cap-provider-config/assets/app.js?h=${FIXTURE_HASH}`,
    );
    // The fixture declares no css — cssUrl must be null, not a 404 URL.
    expect(plugin.app.bundle?.cssUrl).toBeNull();
    // The settings nav earns the plugin a row from enabled + slots; the
    // declared (host-rendered) form face stays false.
    expect(plugin.hasSettings).toBe(false);
    expect(plugin.capabilities).toEqual([]);
  });

  it("keeps contributions the empty fast-metadata shape (bb plugins.ts:198-200)", async () => {
    const response = await request("/api/v1/plugins/contributions");
    expect(response.status).toBe(200);
    expect(await response.json()).toEqual({ cliCommands: [], mentionProviders: [] });
  });

  it("serves the bundle asset immutable under a matching hash", async () => {
    const response = await request(
      `/api/v1/plugins/cap-provider-config/assets/app.js?h=${FIXTURE_HASH}`,
    );
    expect(response.status).toBe(200);
    expect(response.headers.get("content-type")).toBe("text/javascript; charset=utf-8");
    expect(response.headers.get("cache-control")).toBe("public, max-age=31536000, immutable");
    expect(await response.text()).toContain("export {}");
  });

  it("serves no-store under a stale or absent hash", async () => {
    const stale = await request(
      `/api/v1/plugins/cap-provider-config/assets/app.js?h=deadbeefdeadbeef`,
    );
    expect(stale.status).toBe(200);
    expect(stale.headers.get("cache-control")).toBe("no-store");

    const absent = await request("/api/v1/plugins/cap-provider-config/assets/app.js");
    expect(absent.status).toBe(200);
    expect(absent.headers.get("cache-control")).toBe("no-store");
  });

  it("404s unknown ids, unknown files, and undeclared files", async () => {
    const unknownId = await request(
      `/api/v1/plugins/other/assets/app.js?h=${FIXTURE_HASH}`,
    );
    expect(unknownId.status).toBe(404);
    const unknownFile = await request(
      `/api/v1/plugins/cap-provider-config/assets/app.mjs`,
    );
    expect(unknownFile.status).toBe(404);
    // The fixture declares css:false — the css asset is not tracked, so the
    // registry hands back the bb "unknown plugin asset" 404 rather than a
    // missing-file 500.
    const undeclared = await request(
      `/api/v1/plugins/cap-provider-config/assets/app.css?h=${FIXTURE_HASH}`,
    );
    expect(undeclared.status).toBe(404);
  });

  it("keeps the fixture descriptor schema-valid (stage-script contract)", () => {
    // In CI the real descriptor is generated by scripts/stage-bb-spa.sh;
    // this fixture pins the shape both generators must satisfy.
    const descriptor = pluginRegistryDescriptorSchema.parse({
      id: "cap-provider-config",
      name: "Providers",
      description: "fixture",
      icon: "Puzzle",
      version: "0.1.0-test",
      sdkMajor: 0,
      sdkVersion: "0.4.6",
      hash: FIXTURE_HASH,
      files: { js: true, css: false },
    });
    expect(descriptor.hash).toMatch(/^[0-9a-f]{16}$/);
  });
});